"""Add name_translit fields to OrgMember

Revision ID: be48e94fa052
Revises: add_daily_token_usage
Create Date: 2026-03-27 15:13:16.315195
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be48e94fa052'
down_revision: Union[str, None] = 'add_daily_token_usage'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('org_members', sa.Column('name_translit_full', sa.String(length=255), nullable=True))
    op.add_column('org_members', sa.Column('name_translit_initial', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_org_members_name_translit_full'), 'org_members', ['name_translit_full'], unique=False)
    op.create_index(op.f('ix_org_members_name_translit_initial'), 'org_members', ['name_translit_initial'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_org_members_name_translit_initial'), table_name='org_members')
    op.drop_index(op.f('ix_org_members_name_translit_full'), table_name='org_members')
    op.drop_column('org_members', 'name_translit_initial')
    op.drop_column('org_members', 'name_translit_full')
    # ### end Alembic commands ###
